services: 
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend
  express:
    build: .
    ports: 
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - backend
volumes:
  mongo-data: 
    driver: local
networks:
  backend:
    driver: bridge